# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and test app

env:
  APP_PATH: ./app/CloudCalculusCalculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      working-directory: ${{env.APP_PATH}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.APP_PATH}}
      run: dotnet build --no-restore
    - name: Test
      working-directory: ${{env.APP_PATH}}
      run: dotnet test --no-build --verbosity normal
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
