on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    issues: write
    pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        name: Release-Please
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.CLOUD_CALCULUS_RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
      - uses: ./.github/workflows/release_cloudcalculus.yml
        name: Deploy Release
        if: ${{ steps.release.outputs.release_created }}